name: Build and Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    env:
      API_IMAGE: khurshidmurotov/trying-devops-and-ci-cd-2
      FRONTEND_IMAGE: khurshidmurotov/trying-devops-and-ci-cd
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./api/ -t $API_IMAGE:latest
          docker build ./front-end-nextjs/ -t $FRONTEND_IMAGE:latest
      - name: push image to docker hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u khurshidmurotov --password-stdin
          docker push $API_IMAGE:latest
          docker push $FRONTEND_IMAGE:latest
